use_default_settings: true

general:
  debug: false
  instance_name: 'LobeChat Search'

search:
  safe_search: 0
  autocomplete: ''

server:
  port: 8080
  bind_address: '0.0.0.0'
  secret_key: 'CHANGE_THIS_SECRET_KEY_IN_PRODUCTION'
  base_url: false
  image_proxy: false
  method: 'GET'
  default_http_headers:
    X-Content-Type-Options: nosniff
    X-XSS-Protection: 1; mode=block
    X-Download-Options: noopen
    X-Robots-Tag: noindex, nofollow
    Referrer-Policy: no-referrer

ui:
  static_use_hash: false
  default_locale: 'en'
  query_in_title: false
  infinite_scroll: false
  center_alignment: false
  cache_url: 'https://web.archive.org/web/'

outgoing:
  request_timeout: 2.0
  max_request_timeout: 10.0
  useragent_suffix: 'LobeChat'
  pool_connections: 100
  pool_maxsize: 1000
